### ISSUE TITLE
Services

### ISSUE THREAD

**Issue by kevinhury** [booyah/protobuf-objc#47]
Hi, I was wondering if you're planning on supporting Services such as this one

service UserRequest {
    rpc userSearch(Name) returns(User);
}

When I run my proto file (with the messsages Name & User of course) I cannot find any RPC generated.

**Comment by sjchristi** [comment]
Hey kevinhury,

Unfortunately, this branch is being maintained any longer.  I suggest you check out one of these forks that is more up to date:

https://github.com/qzix/protobuf-objc

https://github.com/alexeyxo/protobuf-objc

thanks,
sam
